name: Java CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-jdk-11
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Increment stable version number
      run: |
        CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Current version: $CURRENT_VERSION"
        
        # Remove the "-SNAPSHOT" suffix if present and ensure the version has three parts.
        BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/-SNAPSHOT//')
        if [[ $(echo $BASE_VERSION | awk -F. '{print NF}') -lt 3 ]]; then
          BASE_VERSION="${BASE_VERSION}.0"
        fi
        
        # Extract the patch number and increment it.
        PATCH_VERSION=$(echo $BASE_VERSION | awk -F. '{print $3}')
        NEW_PATCH_VERSION=$((PATCH_VERSION + 1))
        
        # Construct the new stable version without "-SNAPSHOT".
        NEW_VERSION=$(echo $BASE_VERSION | sed "s/\([0-9]*\.[0-9]*\.\)[0-9]*/\1$NEW_PATCH_VERSION/")
        echo "New version: $NEW_VERSION"
        
        # Update the version in pom.xml using the Maven Versions Plugin.
        mvn versions:set -DnewVersion=$NEW_VERSION

    - name: Build and test the project
      run: mvn clean install

    - name: Package the .jar file
      run: mvn package

    - name: Upload .jar as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: target/*.jar

    - name: Commit version update
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add pom.xml
        git commit -m "Updated version to $NEW_VERSION"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
